[project]
name = "atto-weather"
description = "A weather app using PySide6"
authors = [{ name = "Ãngel Carias", email = "lotta.dev@outlook.com" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dynamic = ["version"]
dependencies = [
    "PySide6>=6.9.0",
    "httpx>=0.28.0",
    "tomli>=2.0.0",
    "typing-extensions>=4.11.0",
]

[project.urls]
homepage = "https://github.com/aescarias/atto-weather"

[project.optional-dependencies]
dev = ["ruff>=0.11"]

[project.gui-scripts]
atto_weather = "atto_weather.__main__:run"

[tool.ruff]
target-version = "py39"
line-length = 100
extend-exclude = ["*_rc.py"] # _rc files are generated by rcc

[tool.ruff.lint]
select = ["F", "E", "I"]

[tool.ruff.format]
quote-style = "double"

[tool.setuptools.dynamic]
version = { attr = "atto_weather._self.APP_VERSION" }

[build-system]
requires = ["setuptools>=70"]
build-backend = "setuptools.build_meta"
